# import = ["/home/makaze/.config/alacritty/themes/themes/monokai_pro.toml"]
# import = ["/home/makaze/.config/alacritty/themes/themes/rose-pine-moon.toml"]
# import = ["/home/makaze/.config/alacritty/themes/themes/rose-pine-dawn.toml"]
# import = ["/home/makaze/.config/alacritty/themes/themes/monokai_charcoal.toml"]
# import = ["/home/makaze/.config/alacritty/themes/themes/gruvbox_dark.toml"]
import = ["/home/makaze/.config/alacritty/themes/themes/gruvbox_material_medium_dark.toml"]

live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = true

[cursor]
blink_interval = 500

[cursor.style]
blinking = "Always"
shape = "Beam"

[cursor.vi_mode_style]
shape = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 10

[font.normal]
family = "BlexMono Nerd Font"
style = "Regular"

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

# [mouse.double_click]
# threshold = 300

# [mouse.triple_click]
# threshold = 300

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[window]
opacity = 0.9
dynamic_padding = true

# # Bright only
# [colors.primary]
# foreground = "0x111111"
# background = "0xeeeeee"

[window.padding]
x = 1
y = 1
